Repository chronhq/microservices, pull requests merged in 2019-03, with the labels that each got.

#12 New date limits and actors query
  fetch_actors.py
  fetch_battles.py
  fetch_treaties.py
Labels: A8-looksgood

#15 Add Travis CI
  .gitignore
  .pylintrc
  .travis.yml
  .vscode/settings.json
  fetch_actors.py
  fetch_battles.py
  fetch_cities.py
  fetch_treaties.py
  narratives/napoleon/input.py
  requirements.txt
Labels: A0-pleasereview, F8-enhancement

#14 Disable caching in get_cd_by_wid
  narratives/napoleon/input.py
Labels: A0-pleasereview, F2-bug
